### ISSUE TITLE
出力とグラフの違いについての質問です

### ISSUE THREAD

**Issue by cbh34680** [nikosai/lambda-friends#82]
[Web（GUI）版らむだフレンズ](http://nikosai.github.io/lambda-friends/)

のサイトにて以下のようなマクロを登録しました。
```
succ = \nfx.f(nfx)
plus = \mn. m<succ>n
```

その上で、[出力] タブにて次のラムダ式を入力し [送信] を押します。

`<plus><3>(<plus><1><2>)`

以下のように簡約が行われました。
```
<plus><3>(<plus><1><2>)
-: (macro) = (\mn.m<succ>n)<3>(<plus><1><2>)
...
...
20: (beta) --> \fx.f(f(f(f(f(fx)))))    (normal form)
  = 6 (as nat)
```

同様のことを、[グラフ] のタブにて実行したところ、生成が完了しない状態です。

この両者の違いは何が原因となっているのでしょうか ?

**Comment by nikosai** [comment]
ご質問いただきありがとうございます。

一般に、ラムダ計算では一つのラムダ式の簡約を進める方法はひと通りとは限りません。
[出力] タブでは、これらの簡約方法のうち、一通りの方法を選んで（デフォルトでは最左最外簡約で）簡約を進めていくことになっています。
一方で、[グラフ] のタブは、全通りの簡約方法を試し、全ての経路をグラフ（簡約グラフ）として表示するものです。

例えば、典型例として `<2><2>` （＝2の2乗）を考えます。
これを [出力] タブで実行すると、（マクロ展開を除き）5stepで簡約が終了しますが、同じ式を [グラフ] タブで実行すると、12状態となります。

同様に、今回の `<plus><3>(<plus><1><2>)` は [出力] タブでは（マクロ展開を除き）20stepですが、私の手元で（らむだフレンズのデバッグ機能を使って）確認したところ、この式の簡約グラフの状態数は651でした。

実際、`<plus><3>(<plus><1><2>)` を [グラフ] タブで実行しようとすると、横に幅広く展開されていく様子が見えると思いますが、これは簡約途中の選択肢が多いことを表しています。

このように、簡約グラフが大規模であるために表示しきれていない、ということです。
（大規模なグラフをどのように図示するのが良いかというのはそれだけで研究テーマになるくらい難しいので、今のところそこまでマジメにやろうとは思っていません……）

ちなみに、「グラフの状態数が多すぎて探索しきれない」という同種の問題は、モデル検査などの分野で「状態空間爆発 (state space explosion)」として知られています。

**Comment by cbh34680** [comment]
理解するには、ちゃんと勉強しなければならないみたいですね、、

丁寧な解説をありがとうございました。
